apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailrise
  labels:
    app: mailrise
  namespace: mailrise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailrise
  template:
    metadata:
      labels:
        app: mailrise
    spec:
      containers:
      - name: mailrise
        image: yoryan/mailrise:latest
        ports:
        - containerPort: 25
          name: smtp
        volumeMounts:
          - mountPath: /etc/mailrise.conf
            name: mailrise-config
            subPath: mailrise.conf
      volumes:
        - name: mailrise-config
          configMap:
            name: mailrise-config