apiVersion: v1
kind: Service
metadata:
  name: mailrise-load
  namespace: mailrise
  labels:
    app.kubernetes.io/name: mailrise

spec:
  type: LoadBalancer
  ports:
    - port: 8025
      targetPort: 8025
      protocol: TCP
      name: smtp
  selector:
    app: mailrise