authentik:
  secret_key: "W4VQUreSixCyzkvEkTYt21whI1GDIaypd2B5qQviSlnh5LCvgO7h4xBmRiGvZsXNDuPKRFTVqQeCNlfh"
  postgresql:
    host: web.hosts.harryesses.com
    user: authentik
    password: H92InFmRGHGhYG/BESjR4KyxUgriSTBmxUTukv/AdxQ52bM3
  redis:
    host: web.hosts.harryesses.com
  email:
    # -- SMTP Server emails are sent from, fully optional
    host: "mailrise.mailrise.svc.cluster.local"
    # -- SMTP server port
    port: 25
    # -- SMTP credentials, when left empty, no authentication will be done
    username: ""
    # -- SMTP credentials, when left empty, no authentication will be done
    password: ""
    # -- Use StartTLS. Enable either use_tls or use_ssl, they can't be enabled at the same time.
    use_tls: false
    # -- Use SSL. Enable either use_tls or use_ssl, they can't be enabled at the same time.
    use_ssl: false
    # -- Connection timeout
    timeout: 20
    # -- Email from address, can either be in the format "foo@bar.baz" or "authentik <foo@bar.baz>"
server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingressClassName: nginx
    enabled: true
    hosts:
      - auth.harryesses.com
    tls:
      - hosts:
        - auth.harryesses.com
        secretName: authentik-tls
