apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage-service
spec:
  selector:
    app: homepage
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer