---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
layout:
  Media:
    tab: Other
  Management:
    tab: Other
  Development:
    tab: Other
  Misc:
    tab: Calendar
    style: row
    columns: 2
    header: false


