---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank
- openmeteo:
    latitude: 39.87 
    longitude: -74.25
    timezone: America/New_York
    units: imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
- unifi_console:
    url: https://10.10.1.204:8443
    username: harryesses@harryesses.com
    password: Goyanks12345
