coder:
  ingress:
    # coder.ingress.enable -- Whether to create the Ingress object. If using an
    # Ingress, we recommend not specifying coder.tls.secretNames as the Ingress
    # will handle TLS termination.
    enable: true
    # coder.ingress.className -- The name of the Ingress class to use.
    className: "nginx"
    # coder.ingress.host -- The hostname to match on.
    # Be sure to also set CODER_ACCESS_URL within coder.env[]
    host: "coder.harryesses.com"
    # coder.ingress.wildcardHost -- The wildcard hostname to match on. Should be
    # in the form "*.example.com" or "*-suffix.example.com". If you are using a
    # suffix after the wildcard, the suffix will be stripped from the created
    # ingress to ensure that it is a legal ingress host. Optional if not using
    # applications over subdomains.
    # Be sure to also set CODER_WILDCARD_ACCESS_URL within coder.env[]
    wildcardHost: "*.coder.harryesses.com"
    # coder.ingress.annotations -- The ingress annotations.
    annotations: {
      kubernetes.io/ingress.class: "nginx",
      nginx.ingress.kubernetes.io/proxy-body-size: "100m",
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600",
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600",
      nginx.ingress.kubernetes.io/use-http2: "true",
      nginx.ingress.kubernetes.io/proxy-buffering: "off",
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    }
    # coder.ingress.tls -- The TLS configuration to use for the Ingress.
    tls:
      # coder.ingress.tls.enable -- Whether to enable TLS on the Ingress.
      enable: true
      # coder.ingress.tls.secretName -- The name of the TLS secret to use.
      secretName: "coder-tls"
      # coder.ingress.tls.wildcardSecretName -- The name of the TLS secret to
      # use for the wildcard host.
      wildcardSecretName: "coder-wild-tls"
  env:
    - name: CODER_PG_CONNECTION_URL
      value: "postgresql://coder:SiWg8ce*?eQm,x+@10.10.1.202/coder?sslmode=disable"
    - name: CODER_DERP_FORCE_WEBSOCKETS
      value: "true"

    - name: CODER_WILDCARD_ACCESS_URL
      value: "*.coder.harryesses.com"

    - name: CODER_EXTERNAL_AUTH_0_ID
      value: "gitea"

    - name: CODER_EXTERNAL_AUTH_0_TYPE
      value: "gitea"

    - name: CODER_EXTERNAL_AUTH_0_CLIENT_ID
      value: "e271680e-a5ac-406d-b64f-ee785416d524"

    - name: CODER_EXTERNAL_AUTH_0_CLIENT_SECRET
      value: <path:kv/data/secret/data/coder/oidc#secret>

    - name: CODER_EXTERNAL_AUTH_0_AUTH_URL
      value: "https://git.harryesses.com/login/oauth/authorize"

    - name: CODER_ACCESS_URL
      value: "https://coder.harryesses.com"

    - name: CODER_OIDC_ISSUER_URL
      value: "https://auth.harryesses.com/application/o/coder/"

    - name: CODER_OIDC_EMAIL_DOMAIN
      value: "harryesses.com,jimmysmp.com"

    - name: CODER_OIDC_CLIENT_ID
      value: "FqyKCMekF4o4AE7XdDGJmJQ9vndKlsavRLgWNjzw"

    - name: CODER_OIDC_CLIENT_SECRET
      value: "9pCMdhosoBc7HaxX8n8qKJOj9G91X4zP10FTC4bIDOyiJrTL8hnKG5yE58kYGxtT27kVaZJx19Ou2WWP8kVI9ShxBtPYYizyqwIMWDhYmMhqwAUotWkq2ELkFjUJROuJ"
workspacePVC:
  enabled: true

workspaces:
  additionalVolumes:
    - name: ssh-key
      secret:
        secretName: ssh-key
        defaultMode: 0400

  additionalVolumeMounts:
    - name: ssh-key
      mountPath: /home/coder/.ssh
      readOnly: true